/*
 * Copyright (c) 2010, Oracle.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the distribution.
 *  * Neither the name of Oracle nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED 
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
 */

/* Anagram Game Application */

package com.toy.anagrams.ui;

import com.toy.anagrams.lib.WordLibrary;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.util.Arrays;
import java.util.Comparator;
import java.util.Random;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 * Main window of the Anagram Game application.
 */
public class Anagrams extends JFrame {

	public static void main(String[] args) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels = javax.swing.UIManager
					.getInstalledLookAndFeels();
			for (int idx = 0; idx < installedLookAndFeels.length; idx++)
				if ("Nimbus".equals(installedLookAndFeels[idx].getName())) {
					javax.swing.UIManager.setLookAndFeel(installedLookAndFeels[idx].getClassName());
					break;
				}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Anagrams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Anagrams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Anagrams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Anagrams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		SwingUtilities.invokeLater(new Runnable() {
			public void run() {
				new Anagrams().setVisible(true);
			}
		});
	}

	private int wordIdx = 0;
	private WordLibrary wordLibrary;

	/** Creates new form Anagrams */
	public Anagrams() {
		wordLibrary = WordLibrary.getDefault();

		initComponents();
		getRootPane().setDefaultButton(guessButton);
		scrambledWord.setText(wordLibrary.getScrambledWord(wordIdx));
		pack();
		guessedWord.requestFocusInWindow();
		// Center in the screen
		Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
		Dimension frameSize = getSize();
		setLocation(new Point((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.width) / 2));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		mainPanel = new javax.swing.JPanel();
		scrambledLabel = new javax.swing.JLabel();
		scrambledWord = new javax.swing.JTextField();
		guessLabel = new javax.swing.JLabel();
		guessedWord = new javax.swing.JTextField();
		feedbackLabel = new javax.swing.JLabel();
		buttonsPanel = new javax.swing.JPanel();
		guessButton = new javax.swing.JButton();
		nextTrial = new javax.swing.JButton();
		levelLabel = new javax.swing.JLabel();
		selectLevel = new javax.swing.JComboBox();
		mainMenu = new javax.swing.JMenuBar();
		fileMenu = new javax.swing.JMenu();
		aboutMenuItem = new javax.swing.JMenuItem();
		exitMenuItem = new javax.swing.JMenuItem();

		setTitle("AnagramsRingo");
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				exitForm(evt);
			}
		});

		mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12));
		mainPanel.setMinimumSize(new java.awt.Dimension(297, 200));
		mainPanel.setLayout(new java.awt.GridBagLayout());

		scrambledLabel.setText("問題:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 12, 6);
		mainPanel.add(scrambledLabel, gridBagConstraints);

		scrambledWord.setEditable(false);
		scrambledWord.setColumns(20);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 12, 0);
		mainPanel.add(scrambledWord, gridBagConstraints);

		guessLabel.setDisplayedMnemonic('Y');
		guessLabel.setLabelFor(guessedWord);
		guessLabel.setText("予想:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 6);
		mainPanel.add(guessLabel, gridBagConstraints);

		guessedWord.setColumns(20);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
		mainPanel.add(guessedWord, gridBagConstraints);

		feedbackLabel.setText("並び直して言葉を完成させてください。");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.BELOW_BASELINE;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
		mainPanel.add(feedbackLabel, gridBagConstraints);

		buttonsPanel.setLayout(new java.awt.GridBagLayout());

		guessButton.setMnemonic('G');
		guessButton.setText("回答");
		guessButton.setToolTipText("Guess the scrambled word.");
		guessButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				guessedWordActionPerformed(evt);
			}
		});
		buttonsPanel.add(guessButton, new java.awt.GridBagConstraints());

		nextTrial.setMnemonic('N');
		nextTrial.setText("スキップ");
		nextTrial.setToolTipText("Fetch a new word.");
		nextTrial.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				nextTrialActionPerformed(evt);
			}
		});
		buttonsPanel.add(nextTrial, new java.awt.GridBagConstraints());

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.gridheight = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weighty = 1.0;
		mainPanel.add(buttonsPanel, gridBagConstraints);

		levelLabel.setText("レベル:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		mainPanel.add(levelLabel, gridBagConstraints);

		selectLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "レベル 1", "レベル 2", "レベル 3" }));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		mainPanel.add(selectLevel, gridBagConstraints);

		getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

		fileMenu.setMnemonic('F');
		fileMenu.setText("ファイル");

		aboutMenuItem.setMnemonic('A');
		aboutMenuItem.setText("詳細");
		aboutMenuItem.setToolTipText("詳細");
		aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				aboutMenuItemActionPerformed(evt);
			}
		});
		fileMenu.add(aboutMenuItem);

		exitMenuItem.setMnemonic('E');
		exitMenuItem.setText("終了");
		exitMenuItem.setToolTipText("チームを終了！");
		exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitMenuItemActionPerformed(evt);
			}
		});
		fileMenu.add(exitMenuItem);

		mainMenu.add(fileMenu);

		setJMenuBar(mainMenu);
	}// </editor-fold>//GEN-END:initComponents

	private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_aboutMenuItemActionPerformed
		new About(this).setVisible(true);
	}// GEN-LAST:event_aboutMenuItemActionPerformed

	private void nextTrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTrialActionPerformed
        wordIdx = (wordIdx + 1) % wordLibrary.getSize();
       
        feedbackLabel.setText(" ");
       
        //実装中
        //String[] wordlist = wordLibrary.getWordList();
        //int[] wordlength = new int[wordlist.length];
//        for(int i=0;i<wordLibrary.getWordList().length;i++) {
//        	wordlength[i] = wordlist[i].length();
//        }
//        Arrays.sort(wordlength);
//        String[] wordlist1 = new String[15];
//        String[] wordlist2 = new String[15];
//        String[] wordlist3 = new String[15];
//        for(int i=0;i<15;i++) {
//        	wordlist1[i] = wordlist[i];
//        }
//        for(int i=0;i<15;i++) {
//        	wordlist2[i] = wordlist[i+15];
//        }
//        for(int i=0;i<16;i++) {
//        	wordlist3[i] = wordlist[i+30];
//        }
//        Random rand = new Random();
//        if(selectLevel.getSelectedItem().equals("Level3")) {
//        	wordIdx = rand.nextInt(10);
//        } else {
//        	wordIdx = rand.nextInt(15);
//        }
//        
//        if(selectLevel.getSelectedItem().equals("Level1")) {
//        	scrambledWord.setText(wordlist1[wordIdx]);
//        } else if(selectLevel.getSelectedItem().equals("Level2")) {
//        	scrambledWord.setText(wordlist2[wordIdx]);
//        } else if(selectLevel.getSelectedItem().equals("Level3")) {
//        	scrambledWord.setText(wordlist3[wordIdx]);
//        }
        
        scrambledWord.setText(wordLibrary.getScrambledWord(wordIdx));
        guessedWord.setText("");
        getRootPane().setDefaultButton(guessButton);

        guessedWord.requestFocusInWindow();
    }// GEN-LAST:event_nextTrialActionPerformed

	private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitMenuItemActionPerformed
		System.exit(0);
	}// GEN-LAST:event_exitMenuItemActionPerformed

	private void guessedWordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_guessedWordActionPerformed
		if (wordLibrary.isCorrect(wordIdx, guessedWord.getText())) {
			feedbackLabel.setText("正解！新しい言葉に挑戦してみてね！");
			getRootPane().setDefaultButton(nextTrial);
		} else {
			feedbackLabel.setText("不正解！もう一度挑戦してみてね！");
			guessedWord.setText("");
		}

		guessedWord.requestFocusInWindow();
	}// GEN-LAST:event_guessedWordActionPerformed

	private void exitForm(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_exitForm
		System.exit(0);
	}// GEN-LAST:event_exitForm

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JMenuItem aboutMenuItem;
	private javax.swing.JPanel buttonsPanel;
	private javax.swing.JMenuItem exitMenuItem;
	private javax.swing.JLabel feedbackLabel;
	private javax.swing.JMenu fileMenu;
	private javax.swing.JButton guessButton;
	private javax.swing.JLabel guessLabel;
	private javax.swing.JTextField guessedWord;
	private javax.swing.JLabel levelLabel;
	private javax.swing.JMenuBar mainMenu;
	private javax.swing.JPanel mainPanel;
	private javax.swing.JButton nextTrial;
	private javax.swing.JLabel scrambledLabel;
	private javax.swing.JTextField scrambledWord;
	private javax.swing.JComboBox selectLevel;
	// End of variables declaration//GEN-END:variables

}
